Description of recursdir
recursdir
PURPOSE
OUTFILES = RECURSDIR(BASEDIRECTORY,SEARCHEXPRESSION)
SYNOPSIS
function Outfiles=recursdir(baseDir,searchExpression)
DESCRIPTION
 OUTFILES = RECURSDIR(BASEDIRECTORY,SEARCHEXPRESSION)
 A recursive search to find files that match the search expression
CROSS-REFERENCE INFORMATION
This function calls:
recursdir OUTFILES = RECURSDIR(BASEDIRECTORY,SEARCHEXPRESSION)
This function is called by:
batchkmeans_gui2 BATCHKMEANS_GUI2 MATLAB code for batchkmeans_gui2.fig
freqExport_gui FREQEXPORT_GUI MATLAB code for freqExport_gui.fig
freq_browser FREQ_BROWSER MATLAB code for freq_browser.fig
recursdir OUTFILES = RECURSDIR(BASEDIRECTORY,SEARCHEXPRESSION)
thresholding_gui THRESHOLDING_GUI MATLAB code for thresholding_gui.fig
trace_browser TRACE_BROWSER MATLAB code for trace_browser.fig
SOURCE CODE
function Outfiles=recursdir(baseDir,searchExpression)
% OUTFILES = RECURSDIR(BASEDIRECTORY,SEARCHEXPRESSION)
% A recursive search to find files that match the search expression
%
dstr = dir(baseDir);%search current directory and put results in structure
Outfiles = {};
for II = 1:length(dstr)
    if ~dstr(II).isdir && ~isempty(regexp(dstr(II).name,searchExpression,'match'))
    %look for a match that isn't a directory
        Outfiles{length(Outfiles)+1} = fullfile(baseDir,dstr(II).name);
    elseif dstr(II).isdir && ~strcmp(dstr(II).name,'.') && ~strcmp(dstr(II).name,'..')
    %if it is a directory(and not current or up a level), search in that
        pname = fullfile(baseDir,dstr(II).name);
        OutfilesTemp=recursdir(pname,searchExpression);
        if ~isempty(OutfilesTemp)
        %if recursive search is fruitful, add it to the current list
            Outfiles((length(Outfiles)+1):(length(Outfiles)+length(OutfilesTemp))) = OutfilesTemp;
        end
    end
end